### ISSUE TITLE
Installing dateutil with pip?

### ISSUE THREAD

**Issue by dsentinel** [conda-forge/python-dateutil-feedstock#17] opened 2018-06-04 23:42 UTC
Issue:
Constructor fails to install dateutil

Shouldn't
https://github.com/conda-forge/python-dateutil-feedstock/blob/b2ef301d4ad77d222bd3caa419bf47a50c1405e0/recipe/meta.yaml#L14

be python `python setup.py ...`

related to:
 #https://github.com/conda/constructor/issues/201
I know that constructor should probably handle this,
but in general don't we want conda packages to be managed by conda, and not pip?

**Comment by ocefpaf** [comment] 2018-06-05 11:12
I don't think the issue is with `pip` but the `noarch` support on constructor.

@msarahan what are the news on `constructor` supporting `noarch`?

**Comment by dsentinel** [comment] 2018-06-06 16:14
Thanks for the response.... Wait to hear from @msarahan.

I assume that dateutil is only available as noarch, is it possible build out arch packages?

Any comment about using pip instead of setup.py?

**Comment by pganssle** [comment] 2018-10-19 16:23
Please don't use `setup.py` to install dateutil. There's no guarantee that it will work, as `setup.py` will ignore `pyproject.toml`.  Pip is the correct way to install dateutil (and all packages where it's possible to use `pip` for it).

**Comment by ocefpaf** [comment] 2018-10-19 18:09
> Please don't use `setup.py` to use dateutil. There's no guarantee that it will work, as `setup.py` will ignore `pyproject.toml`. Pip is the correct way to install dateutil (and all packages where it's possible to use `pip` for it).

:+1: In conda-forge we are recommending only `pip` and replacing `setup.py` everywhere. If you have anything to add to our docs please let me know:

https://conda-forge.org/docs/meta.html#use-pip

PS: closing this b/c it is ultimately a bug in constructor and there is little we can do here. Sorry @dsentinel.

**Closed as completed by ocefpaf** 2018-10-19 18:09 UTC
